# Generated by Django 2.2.10 on 2021-04-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'text'), (2, 'single_select'), (3, 'several_select')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('user', 'question')},
        ),
    ]
